### ISSUE TITLE
Rock Images are not accessible

### ISSUE THREAD

**Issue by craigchamplin** [jamessergeant/seqreg_tpp#1]
The link to the image set is not working.  It is also broken on the main QUT dataset page.

I am doing my dissertation on anomaly recognition with SLAM.  It is a question of recognizing anomalous texture amongst normal texture.  This dataset looks like it would be useful for proving some initial concepts.  

Sure would be great if I could access it!  :-) 

Thank you.

**Comment by jamessergeant** [comment]
Thanks for pointing this out @craigchamplin. I believe the cloud service it is hosted on made some changes a little while back which broke all links. I will correct this in a couple of hours when I get in to work. Cheers.

**Comment by jamessergeant** [comment]
Hi @craigchamplin I have updated the link. Please let me know if you have any further trouble. I hope it is useful for your work.

**Comment by craigchamplin** [comment]
Thanks James!  This is what I needed.  :-)
